
name: CICD

on: 
  workflow_dispatch:
    
      
    


jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo " code clone from github"
        
  build:
    needs: [code]
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker container
        run: echo " Docker container build"

  test: 
   needs: [code,build]
   runs-on: ubuntu-latest

   steps:
     - name: Test the code
       run: echo "Code test "
       
  deploy: 
   needs: [code,build,test]
   runs-on: ubuntu-latest

   steps:
     - name: Deploy the code
       run: echo "Deploying of code"
       
   

